Task1

diff --git a/module3_task1/Makefile b/module3_task1/Makefile
--- a/module3_task1/Makefile
+++ b/module3_task1/Makefile
@@ -1,13 +1,25 @@
-build:		## Build with Hugo
+lint: ## Lint
+	shellcheck setup.sh >/dev/null 2>&1 || echo "Lint Failed"
+
+build: ## Build with Hugo
 	hugo
 
-clean:		## Delete the dist/ directory
+unit-tests: ## Unit Tests
+	echo "PASS"
+
+integration-tests: ## Integration Tests
+	echo "PASS"
+
+validate: ## Validate
+	echo "PASS"
+
+clean: ## Delete the dist/ directory
 	rm -rf dist
 
-post:		## Create a new post
+post: ## Create a new post
 	echo '---' >> ./content/posts/$(POST_NAME).md
 	echo "title: $(POST_TITLE)" >> ./content/posts/$(POST_NAME).md
 	echo '---' >> ./content/posts/$(POST_NAME).md
 
-help:		## Displays help for this makefile
+help: ## Displays help for this makefile
 	@grep -E '^[a-zA-Z0-9 -]+:.*#'  Makefile | sort | while read -r l; do printf "\033[1;32m$$(echo $$l | cut -f 1 -d':')\033[00m:$$(echo $$l | cut -f 2- -d'#')\n"; done
